/* Quiz Center rebuild. Uses the existing Supabase tables: subjects, quizzes, questions, admin_users. */
const sbReady=!!(window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&!String(window.SUPABASE_URL).startsWith('YOUR_')&&!String(window.SUPABASE_ANON_KEY).startsWith('YOUR_'));
const sb=sbReady?window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id), letters=['A','B','C','D'];
// Admin identity is public; authorization still depends on Supabase Auth + admin_users.
const ADMIN_EMAIL='29jul2005@gmail.com';
let authMode='learner',user=null,isAdmin=false,activeSubject=null,activeQuiz=null,subjects=[],quizzes=[],dbQuestions=[],current=0,answers={},submitted={};
function message(text,type='notice'){const el=$('authMsg');el.textContent=text;el.className='notice'+(type==='error'?' error':type==='success'?' success':'');el.classList.remove('hidden')}
function hideMessage(){ $('authMsg').textContent='';$('authMsg').classList.add('hidden') }
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function showOnly(id){['auth','subjects','quiz','result'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function setHeader(title,subtitle){$('pageTitle').textContent=title;$('pageSubtitle').textContent=subtitle||''}
function setAuthMode(mode){authMode=mode;const admin=mode==='admin';$('learnerTab').className=admin?'ghost':'primary active';$('adminTab').className=admin?'primary active':'ghost';$('emailWrap').classList.toggle('hidden',admin);$('email').required=!admin;$('email').value=admin?ADMIN_EMAIL:'';$('adminIdentity').textContent=ADMIN_EMAIL;$('passwordWrap').classList.toggle('hidden',!admin);$('password').required=admin;$('password').value='';$('authSubmit').textContent=admin?'ยืนยันรหัสผ่านแอดมิน':'เข้าสู่ระบบ';hideMessage()}
$('learnerTab').onclick=()=>setAuthMode('learner');$('adminTab').onclick=()=>setAuthMode('admin');
$('authForm').addEventListener('submit',async e=>{e.preventDefault();hideMessage();if(!sb){message('ยังไม่ได้ตั้งค่า Supabase ใน config.js','error');return}const email=(authMode==='admin'?ADMIN_EMAIL:$('email').value).trim().toLowerCase();if(!email){message('กรุณากรอกอีเมล','error');return}const btn=$('authSubmit');btn.disabled=true;try{if(authMode==='learner'){isAdmin=false;user={email,mode:'learner'};localStorage.setItem('quiz_current_email',email);localStorage.removeItem('quiz_admin_mode');await startLearner()}else{const password=$('password').value;if(!password){message('กรุณากรอกรหัสผ่านแอดมิน','error');return}const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;if(!data.user)throw new Error('ไม่พบผู้ใช้');const {data:adminOk,error:adminErr}=await sb.rpc('is_quiz_admin');if(adminErr)throw new Error('ตรวจสิทธิ์แอดมินไม่สำเร็จ กรุณาตรวจ SQL ตั้งค่าระบบ: '+adminErr.message);if(adminOk!==true){await sb.auth.signOut();throw new Error('บัญชีนี้ยังไม่ได้รับสิทธิ์แอดมิน')}isAdmin=true;user={email:data.user.email||email,id:data.user.id,mode:'admin'};localStorage.removeItem('quiz_current_email');localStorage.setItem('quiz_admin_mode','true');await startAdmin()}}catch(err){message(err?.message||'เข้าสู่ระบบไม่สำเร็จ','error')}finally{btn.disabled=false}});
$('account').onclick=logout;
async function startLearner(){isAdmin=false;showOnly('subjects');$('account').textContent=user.email+' · ผู้เรียน (แตะเพื่อออก)';setHeader('ศูนย์รวมแบบทดสอบ','เลือกวิชาที่ต้องการติว');await renderSubjects()}
async function startAdmin(){showOnly('subjects');$('account').textContent=user.email+' · แอดมิน (แตะเพื่อออก)';setHeader('ศูนย์รวมแบบทดสอบ','โหมดผู้ดูแลระบบ');await renderSubjects()}
async function logout(){if(!user)return;if(!confirm('ออกจากระบบหรือไม่?'))return;if(user.mode==='admin'&&sb)await sb.auth.signOut();user=null;isAdmin=false;activeSubject=null;activeQuiz=null;localStorage.removeItem('quiz_current_email');localStorage.removeItem('quiz_admin_mode');$('account').textContent='ยังไม่ได้เข้าสู่ระบบ';showOnly('auth');setHeader('Quiz Center','ศูนย์รวมแบบทดสอบ');setAuthMode('learner')}
async function getSubjects(){const r=await sb.from('subjects').select('*').eq('is_published',true).order('sort_order').order('name');if(r.error)throw r.error;return r.data||[]}
async function getQuizzes(subjectId){const r=await sb.from('quizzes').select('*').eq('subject_id',subjectId).eq('is_published',true).order('sort_order').order('created_at');if(r.error)throw r.error;return r.data||[]}
async function loadQuestions(quizId){const r=await sb.from('questions').select('*').eq('quiz_id',quizId).order('sort_order').order('created_at');if(r.error)throw r.error;return (r.data||[]).map(q=>({id:q.id,question:q.question,options:{A:q.option_a,B:q.option_b,C:q.option_c,D:q.option_d},answer:String(q.answer||'').toUpperCase(),explanation:q.explanation||''}))}
function progressKey(id){return 'quiz_progress_v3_'+encodeURIComponent(user?.email||'')+'_'+id}
function readProgress(id){try{return JSON.parse(localStorage.getItem(progressKey(id)))||{answers:{},submitted:{},viewed:false}}catch{return {answers:{},submitted:{},viewed:false}}}
function saveProgress(){if(!user||!activeQuiz)return;localStorage.setItem(progressKey(activeQuiz.id),JSON.stringify({answers,submitted,viewed:true,updated_at:new Date().toISOString()}))}
async function renderSubjects(){const box=$('subjects');box.innerHTML=`<div class="row" style="justify-content:space-between"><div><div class="small">QUIZ CENTER</div><h2>เลือกวิชา</h2><p class="muted">เลือกวิชาเพื่อดูบทเรียนและชุดติวสอบ</p></div>${isAdmin?'<button class="primary" id="adminBtn" type="button">⚙ จัดการเนื้อหา</button>':''}</div><div id="subjectGrid" class="grid"></div><div id="subjectMsg" class="notice hidden"></div>`;if(isAdmin)$('adminBtn').onclick=showAdmin;const grid=$('subjectGrid');try{subjects=await getSubjects();if(!subjects.length){$('subjectMsg').textContent='ยังไม่มีวิชาที่เผยแพร่ในระบบ หรือยังไม่ได้ตั้งค่าสิทธิ์อ่านข้อมูล';$('subjectMsg').classList.remove('hidden');return}for(const s of subjects){const b=document.createElement('button');b.className='tile';b.type='button';b.innerHTML=`<div style="font-size:28px">${esc(s.icon||'📚')}</div><h3>${esc(s.name)}</h3><p>${esc(s.description||'เลือกเพื่อดูบทเรียน')}</p>`;b.onclick=()=>showQuizzesFor(s);grid.appendChild(b)}}catch(e){$('subjectMsg').textContent='โหลดวิชาไม่สำเร็จ: '+(e.message||e);$('subjectMsg').classList.remove('hidden')}}
async function showQuizzesFor(subject){activeSubject=subject;showOnly('subjects');setHeader(subject.name,'เลือกบทหรือชุดติวสอบ');const box=$('subjects');box.innerHTML=`<div class="row" style="justify-content:space-between"><div><h2>${esc(subject.icon||'📚')} ${esc(subject.name)}</h2><p class="muted">เลือกชุดข้อสอบที่ต้องการทำ</p></div><div class="row">${isAdmin?'<button class="primary" id="adminBtn" type="button">⚙ จัดการเนื้อหา</button>':''}<button class="ghost" id="backSubjects" type="button">← วิชา</button></div></div><div id="quizGrid" class="grid"></div><div id="quizMsg" class="notice hidden"></div>`;$('backSubjects').onclick=()=>{setHeader('ศูนย์รวมแบบทดสอบ','เลือกวิชาที่ต้องการติว');renderSubjects()};if(isAdmin)$('adminBtn').onclick=showAdmin;if(isAdmin){const addQuizBtn=document.createElement('button');addQuizBtn.id='addQuizForSubject';addQuizBtn.className='primary';addQuizBtn.type='button';addQuizBtn.textContent='＋ เพิ่มชุดข้อสอบในวิชานี้';addQuizBtn.style.margin='12px 0';box.insertBefore(addQuizBtn,box.querySelector('#quizGrid'));addQuizBtn.onclick=()=>showQuizImport(subject)}try{quizzes=await getQuizzes(subject.id);const grid=$('quizGrid');if(!quizzes.length){$('quizMsg').textContent='วิชานี้ยังไม่มีชุดข้อสอบที่เผยแพร่';$('quizMsg').classList.remove('hidden');return}for(const q of quizzes){const p=readProgress(q.id),done=Object.keys(p.submitted||{}).length,total=q.quiz_size||30,b=document.createElement('button');b.className='tile';b.type='button';b.innerHTML=`<div class="small">${esc(q.kind_label||q.kind||'แบบทดสอบ')}</div><h3>${esc(q.title)}</h3><p>${esc(q.description||'')}</p><div class="progress"><div style="width:${Math.min(100,Math.round(done/total*100))}%"></div></div><div class="small">ความคืบหน้า ${done}/${total}</div>`;b.onclick=()=>openQuiz(q);grid.appendChild(b)}}catch(e){$('quizMsg').textContent='โหลดชุดข้อสอบไม่สำเร็จ: '+(e.message||e);$('quizMsg').classList.remove('hidden')}}
async function openQuiz(q){activeQuiz=q;try{dbQuestions=await loadQuestions(q.id);if(!dbQuestions.length)throw new Error('ชุดข้อสอบนี้ยังไม่มีคำถามในตาราง questions');const p=readProgress(q.id);answers=p.answers||{};submitted=p.submitted||{};current=Math.max(0,dbQuestions.findIndex(x=>!submitted[x.id]));showOnly('quiz');setHeader(q.title,activeSubject.name+' · '+dbQuestions.length+' ข้อ');renderQuestion()}catch(e){alert(e.message||'เปิดชุดข้อสอบไม่สำเร็จ')}}
function renderQuestion(){if(!activeQuiz)return;const done=Object.keys(submitted).length;if(done>=dbQuestions.length){showResult();return}if(current>=dbQuestions.length)current=0;const q=dbQuestions[current];$('qnum').textContent=`ข้อ ${current+1}/${dbQuestions.length}`;$('progressText').textContent=`ตอบแล้ว ${done}/${dbQuestions.length}`;$('bar').style.width=(done/dbQuestions.length*100)+'%';$('question').textContent=q.question;$('options').innerHTML='';$('feedback').classList.add('hidden');$('submit').classList.toggle('hidden',!!submitted[q.id]);$('next').classList.toggle('hidden',!submitted[q.id]);$('submit').disabled=!answers[q.id];$('badge').textContent=submitted[q.id]?'ตอบแล้ว':'ยังไม่ตอบ';for(const l of letters){const b=document.createElement('button');b.type='button';b.className='option'+(answers[q.id]===l?' selected':'')+(submitted[q.id]&&q.answer===l?' correct':'')+(submitted[q.id]&&answers[q.id]===l&&answers[q.id]!==q.answer?' wrong':'');b.disabled=!!submitted[q.id];b.innerHTML=`<span class="letter">${l}</span><span>${esc(q.options[l]||'')}</span>`;b.onclick=()=>{answers[q.id]=l;saveProgress();renderQuestion()};$('options').appendChild(b)}if(submitted[q.id]){$('feedback').className='feedback '+(submitted[q.id]===q.answer?'good':'bad');$('fbtitle').textContent=submitted[q.id]===q.answer?'✓ ถูกต้อง':'✕ คำตอบที่ถูกคือ '+q.answer;$('explanation').textContent=q.explanation||'';$('feedback').classList.remove('hidden');$('next').textContent=current===dbQuestions.length-1?'ดูผลคะแนน →':'ข้อถัดไป →'}}
$('submit').onclick=()=>{const q=dbQuestions[current];if(!answers[q.id])return;submitted[q.id]=answers[q.id];saveProgress();renderQuestion()};$('next').onclick=()=>{if(current<dbQuestions.length-1){current++;renderQuestion()}else showResult()};$('quizBack').onclick=()=>showQuizzesFor(activeSubject);$('reset').onclick=()=>{if(confirm('ล้างคำตอบของชุดนี้และเริ่มใหม่หรือไม่?')){answers={};submitted={};current=0;saveProgress();renderQuestion()}};
function showResult(){showOnly('result');const correct=dbQuestions.filter(q=>submitted[q.id]===q.answer).length;$('score').textContent=`${correct} / ${dbQuestions.length} คะแนน`;$('resultText').textContent=`ทำไปแล้ว ${Object.keys(submitted).length} จาก ${dbQuestions.length} ข้อ`;setHeader('ผลคะแนน',activeQuiz.title)}$('resultBack').onclick=()=>showQuizzesFor(activeSubject);$('retake').onclick=()=>{answers={};submitted={};current=0;saveProgress();showOnly('quiz');setHeader(activeQuiz.title,activeSubject.name);renderQuestion()};$('review').onclick=()=>{current=0;showOnly('quiz');setHeader(activeQuiz.title,activeSubject.name);renderQuestion()};
function showAdmin(){if(!isAdmin){alert('ไม่มีสิทธิ์เข้าถึงหน้านี้');return}showOnly('subjects');setHeader('จัดการเนื้อหา','ผู้ดูแลระบบ');$('subjects').innerHTML=`<div class="row" style="justify-content:space-between"><div><div class="small">ADMIN</div><h2>จัดการ Quiz Center</h2><p class="muted">เพิ่มวิชา แล้วเข้าไปในวิชาเพื่อเพิ่มชุดข้อสอบ</p></div><button id="adminBack" class="ghost" type="button">← หน้าหลัก</button></div><div class="admin-box"><h3>เพิ่มวิชา</h3><label>ชื่อวิชา</label><input id="newSubjectName" placeholder="เช่น PPM"><label>ไอคอน</label><input id="newSubjectIcon" placeholder="📊"><label>คำอธิบาย</label><input id="newSubjectDesc" placeholder="รายละเอียดวิชา"><button id="addSubject" class="primary" style="margin-top:12px" type="button">เพิ่มวิชา</button><p id="adminMsg1" class="small"></p></div><p class="small">หลังเพิ่มวิชา ระบบจะกลับไปหน้าหลัก จากนั้นเลือกวิชาที่ต้องการเพิ่มชุดข้อสอบ</p>`;$('adminBack').onclick=()=>{setHeader('ศูนย์รวมแบบทดสอบ','เลือกวิชาที่ต้องการติว');renderSubjects()};$('addSubject').onclick=addSubject}
function showQuizImport(subject){if(!isAdmin){alert('ไม่มีสิทธิ์เข้าถึงหน้านี้');return}activeSubject=subject;showOnly('subjects');setHeader('เพิ่มชุดข้อสอบ',subject.name);$('subjects').innerHTML=`<div class="row" style="justify-content:space-between"><div><div class="small">ADMIN · ${esc(subject.name)}</div><h2>เพิ่มชุดข้อสอบ</h2><p class="muted">ชุดข้อสอบนี้จะถูกบันทึกในวิชา ${esc(subject.name)}</p></div><button id="importBack" class="ghost" type="button">← กลับไปหน้าวิชา</button></div><div class="admin-box"><h3>นำเข้าชุดข้อสอบจาก GPT</h3><p class="muted">วาง JSON ที่มี quiz.title และ quiz.questions ไม่จำเป็นต้องระบุชื่อวิชา เพราะเลือกวิชาไว้แล้ว</p><textarea id="importJson" placeholder='{"quiz":{"title":"บทที่ 1","type":"chapter","quiz_size":2,"questions":[{"question":"คำถาม?","options":{"A":"ตัวเลือก A","B":"ตัวเลือก B","C":"ตัวเลือก C","D":"ตัวเลือก D"},"answer":"B","explanation":"คำอธิบาย"}]}}'></textarea><button id="importQuiz" class="primary" style="margin-top:12px" type="button">นำเข้าข้อสอบ</button><p id="adminMsg2" class="small"></p></div>`;$('importBack').onclick=()=>showQuizzesFor(subject);$('importQuiz').onclick=()=>importQuiz(subject)}
async function addSubject(){const msg=$('adminMsg1'),name=$('newSubjectName').value.trim();if(!name){msg.textContent='กรุณากรอกชื่อวิชา';return}try{const r=await sb.from('subjects').insert({name,icon:$('newSubjectIcon').value.trim()||'📚',description:$('newSubjectDesc').value.trim(),is_published:true,sort_order:0}).select().single();if(r.error)throw r.error;msg.textContent='เพิ่มวิชาแล้ว กำลังกลับหน้าหลัก';msg.className='success';await renderSubjects();setHeader('ศูนย์รวมแบบทดสอบ','เลือกวิชาที่ต้องการติว')}catch(e){msg.textContent='เพิ่มวิชาไม่สำเร็จ: '+e.message;msg.className='error'}}
function parseImport(raw){const data=JSON.parse(raw.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));if(Array.isArray(data))throw new Error('กรุณาใช้ JSON ที่มี subject และ quiz.questions');if(data.quiz?.questions)return data;if(data.questions&&data.subject)return {...data,quiz:data};throw new Error('ไม่พบ subject หรือ quiz.questions ใน JSON')}
async function importQuiz(selectedSubject){const msg=$('adminMsg2');msg.textContent='กำลังนำเข้า...';try{const raw=$('importJson').value.trim();let data;try{data=JSON.parse(raw.replace(/^```(?:json)?\\s*/i,'').replace(/\\s*```$/,''))}catch(e){throw new Error('JSON ไม่ถูกต้อง กรุณาตรวจรูปแบบแล้วลองใหม่')}const qd=data.quiz||data;if(!selectedSubject)throw new Error('ไม่พบวิชาที่เลือก');if(!qd.title||!Array.isArray(qd.questions)||!qd.questions.length)throw new Error('ต้องระบุ quiz.title และ quiz.questions');for(const [i,q] of qd.questions.entries()){if(!q.question||!['A','B','C','D'].every(k=>q.options?.[k])||!['A','B','C','D'].includes(String(q.answer).toUpperCase()))throw new Error(`ข้อ ${i+1}: ต้องมีคำถาม ตัวเลือก A-D และคำตอบ A-D`)}const type=qd.type||'chapter';const qr=await sb.from('quizzes').insert({subject_id:selectedSubject.id,title:qd.title,kind:type,kind_label:qd.kind_label||({'chapter':'บท','combined':'บทรวม','midterm':'ติวสอบกลางภาค','final':'ติวสอบปลายภาค'}[type]||'แบบทดสอบ'),description:qd.description||'',quiz_size:Number(qd.quiz_size||qd.questions.length),is_published:true,sort_order:0}).select().single();if(qr.error)throw qr.error;const rows=qd.questions.map((q,i)=>({quiz_id:qr.data.id,question:q.question,option_a:q.options.A,option_b:q.options.B,option_c:q.options.C,option_d:q.options.D,answer:String(q.answer).toUpperCase(),explanation:q.explanation||'',sort_order:i}));const ir=await sb.from('questions').insert(rows);if(ir.error){await sb.from('quizzes').delete().eq('id',qr.data.id);throw ir.error}alert(`นำเข้าสำเร็จ: ${selectedSubject.name} / ${qd.title} / ${rows.length} ข้อ ระบบจะกลับหน้าหลัก`);activeSubject=null;$('importJson').value='';await renderSubjects();setHeader('ศูนย์รวมแบบทดสอบ','เลือกวิชาที่ต้องการติว')}catch(e){msg.textContent='นำเข้าไม่สำเร็จ: '+(e.message||e);msg.className='error'}}
(async function init(){if(!sb){showOnly('auth');message('ยังไม่ได้ตั้งค่า Supabase ใน config.js','error');return}try{const {data}=await sb.auth.getSession();if(data?.session?.user){const {data:ok,error}=await sb.rpc('is_quiz_admin');if(!error&&ok===true){isAdmin=true;user={email:data.session.user.email,id:data.session.user.id,mode:'admin'};await startAdmin();return}await sb.auth.signOut()}const saved=localStorage.getItem('quiz_current_email');if(saved){user={email:saved,mode:'learner'};await startLearner()}else{showOnly('auth');setHeader('Quiz Center','ศูนย์รวมแบบทดสอบ')}}catch(e){showOnly('auth');message('เริ่มต้นระบบไม่สำเร็จ: '+(e.message||e),'error')}})();
