const sbReady=window.SUPABASE_URL&&!window.SUPABASE_URL.startsWith("YOUR_")&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_ANON_KEY.startsWith("YOUR_");const sb=sbReady?supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY):null;let user=null,mode="login",current=0,answers={},submitted={},score=0;const $=x=>document.getElementById(x), letters="ABCD".split("");
function localSave(){localStorage.setItem("lawQuizProgress",JSON.stringify({answers,submitted,score,current}))}
async function save(){localSave();if(!sb||!user){$("saveStatus").textContent="บันทึกไว้ในเครื่องนี้";return}const {error}=await sb.from("quiz_progress").upsert({user_id:user.id,answers,submitted,score,completed:Object.keys(submitted).length===50,updated_at:new Date().toISOString()});$("saveStatus").textContent=error?"บันทึกออนไลน์ไม่สำเร็จ":"บันทึกคำตอบแล้ว"}
function nextUnanswered(){for(let i=0;i<50;i++)if(!submitted[i+1])return i;return 49}
async function load(){if(sb&&user){let r=await sb.from("quiz_progress").select("*").eq("user_id",user.id).maybeSingle();if(!r.error&&r.data){answers=r.data.answers||{};submitted=r.data.submitted||{};score=r.data.score||0;current=nextUnanswered();return}}try{let d=JSON.parse(localStorage.getItem("lawQuizProgress")||"{}");answers=d.answers||{};submitted=d.submitted||{};score=d.score||0;current=nextUnanswered()}catch{}}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function render(){if(Object.keys(submitted).length===50){$("quiz").classList.add("hidden");$("result").classList.remove("hidden");$("score").textContent=score+" / 50";let p=score*2;$("resultText").textContent=p>=80?"ระดับดีมาก — ทบทวนเฉพาะข้อที่ผิด":p>=60?"ผ่านระดับพื้นฐาน แต่ยังมีบางหัวข้อที่ควรทบทวน":"ควรกลับไปทบทวนเนื้อหาหลักแล้วลองทำใหม่";return}$("result").classList.add("hidden");$("quiz").classList.remove("hidden");let q=QUESTIONS[current],done=!!submitted[q.id];$("qnum").textContent="ข้อ "+q.id;$("progressText").textContent="ข้อ "+q.id+" / 50 • ตอบแล้ว "+Object.keys(submitted).length+" ข้อ";$("bar").style.width=((q.id-1)/50*100)+"%";$("question").textContent=q.question;$("badge").textContent=done?(submitted[q.id]===q.answer?"ถูก":"ผิด"):"ยังไม่ตอบ";$("options").innerHTML="";letters.forEach(l=>{let b=document.createElement("button");b.className="option";if(answers[q.id]===l)b.classList.add("selected");if(done&&q.answer===l)b.classList.add("correct");if(done&&answers[q.id]===l&&answers[q.id]!==q.answer)b.classList.add("wrong");b.disabled=done;b.innerHTML='<span class="letter">'+l+'</span><span>'+esc(q.options[l])+'</span>';b.onclick=()=>{answers[q.id]=l;render();save()};$("options").appendChild(b)});if(done){$("feedback").className="feedback "+(submitted[q.id]===q.answer?"good":"bad");$("feedback").classList.remove("hidden");$("fbtitle").textContent=submitted[q.id]===q.answer?"✓ ถูกต้อง":"✕ ยังไม่ถูก — คำตอบที่ถูกคือ "+q.answer;$("explanation").textContent=q.explanation;$("submit").classList.add("hidden");$("next").classList.remove("hidden");$("next").textContent=current===49?"ดูผลคะแนน →":"ไปข้อถัดไป →"}else{$("feedback").classList.add("hidden");$("submit").classList.remove("hidden");$("next").classList.add("hidden");$("submit").disabled=!answers[q.id]}}
$("submit").onclick=async()=>{let q=QUESTIONS[current];if(!answers[q.id])return;submitted[q.id]=answers[q.id];if(answers[q.id]===q.answer)score++;await save();render()}
$("next").onclick=()=>{if(current<49){current++;render();save()}else render()}
$("reset").onclick=async()=>{if(confirm("ล้างคำตอบทั้งหมดและเริ่มใหม่หรือไม่?")){answers={};submitted={};score=0;current=0;await save();render()}}
$("retake").onclick=async()=>{answers={};submitted={};score=0;current=0;await save();render()}
$("review").onclick=()=>{current=0;render()}
$("loginTab").onclick=()=>{mode="login";$("loginTab").classList.add("active");$("signupTab").classList.remove("active");$("authSubmit").textContent="เข้าสู่ระบบ"}
$("signupTab").onclick=()=>{mode="signup";$("signupTab").classList.add("active");$("loginTab").classList.remove("active");$("authSubmit").textContent="สมัครบัญชี"}
$("authForm").onsubmit=async e=>{e.preventDefault();if(!sb){$("authMsg").textContent="ยังไม่ได้ตั้งค่า Supabase ใน config.js";return}let email=$("email").value.trim(),password=$("password").value,r=mode==="signup"?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error){$("authMsg").textContent=r.error.message;return}if(mode==="signup"&&!r.data.session){$("authMsg").textContent="สมัครสำเร็จ กรุณาตรวจอีเมลถ้าระบบเปิดการยืนยันอีเมล"}else{user=r.data.user;await start()}}
async function start(){await load();$("account").textContent=user.email;$("auth").classList.add("hidden");render()}
(async()=>{if(!sb){$("authMsg").textContent="เว็บพร้อมแล้ว แต่ต้องตั้งค่า Supabase เพื่อเปิดระบบบัญชีและบันทึกข้ามอุปกรณ์"}else{let r=await sb.auth.getSession();if(r.data.session){user=r.data.session.user;await start()}}})()